In [1]:
import numpy as np

In [2]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
a2 = np.array([[1, 2, 3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [4]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [5]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [6]:
a1.shape

(3,)

In [7]:
a2.shape

(2, 3)

In [8]:
a3.shape

(2, 3, 3)

In [9]:
import pandas as pd

In [10]:
df = pd.DataFrame(a2)

In [11]:
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5

In [12]:
sample_arr = np.array([1, 2, 3])
sample_arr

array([1, 2, 3])

In [14]:
ones = np.ones((2, 3))

In [15]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [18]:
rand_array = np.random.randint(0, 10, size=(3, 5))
rand_array

array([[1, 0, 2, 9, 8],
       [5, 7, 5, 8, 0],
       [0, 6, 3, 7, 6]])

In [19]:
a1

array([1, 2, 3])

In [20]:
a1 + ones

array([[2., 3., 4.],
       [2., 3., 4.]])

In [22]:
a1 - ones

array([[0., 1., 2.],
       [0., 1., 2.]])

In [23]:
a1 * ones

array([[1., 2., 3.],
       [1., 2., 3.]])

In [24]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [25]:
a1 * a2

array([[ 1. ,  4. ,  9. ],
       [ 4. , 10. , 19.5]])

In [26]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [27]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [28]:
a2 + a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [29]:
a2.reshape(2, 3, 1)

array([[[1. ],
        [2. ],
        [3. ]],

       [[4. ],
        [5. ],
        [6.5]]])

In [30]:
a2_rs = a2.reshape(2, 3, 1)

In [31]:
a2_rs * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 21. ,  24. ,  27. ]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [32]:
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3. , 6.5]])

In [33]:
a2.T * a3

ValueError: operands could not be broadcast together with shapes (3,2) (2,3,3) 

In [34]:
np.random.seed(0)
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [35]:
weekly_sales = pd.DataFrame(sales_amounts, index=["Mon", "Tues", "Wed", "Thurs", "Fri"],
                            columns=["Almond butter", "Peanut butter", "Cashew butter"])
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [36]:
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [38]:
butter_prices = pd.DataFrame(prices.reshape(1, 3),
                             index=["Price"],
                             columns=["Almond butter", "Peanut butter", "Cashew butter"])
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [40]:
total_sales = prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [41]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

Mon  Tues  Wed  Thurs  Fri
Price  240   138  458    232  142

In [44]:
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total ($)
Mon               12             15              0        240
Tues               3              3              7        138
Wed                9             19             18        458
Thurs              4              6             12        232
Fri                1              6              7        142

In [45]:
a1

array([1, 2, 3])

In [46]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [47]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [48]:
a1 >= a2

array([[ True,  True,  True],
       [False, False, False]])

In [49]:
a1 == a2

array([[ True,  True,  True],
       [False, False, False]])

In [50]:
np.equal(a1, a2)

array([[ True,  True,  True],
       [False, False, False]])

In [51]:
rand_array

array([[1, 0, 2, 9, 8],
       [5, 7, 5, 8, 0],
       [0, 6, 3, 7, 6]])

In [52]:
np.sort(rand_array)

array([[0, 1, 2, 8, 9],
       [0, 5, 5, 7, 8],
       [0, 3, 6, 6, 7]])

In [53]:
np.argsort(rand_array)

array([[1, 0, 2, 4, 3],
       [4, 0, 2, 1, 3],
       [0, 2, 1, 4, 3]])

In [54]:
np.argmax(a3)

17

In [56]:
np.argmax(rand_array, axis=0)

array([1, 1, 1, 0, 0])

# Working with Images

In [59]:
from matplotlib.image import imread

In [60]:
panda = imread("images/panda.png")
type(panda)

numpy.ndarray

In [61]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [62]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [63]:
car = imread("images/car-photo.png")

In [64]:
dog = imread("images/dog-photo.png")

In [65]:
dog[:1]

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]]], dtype=float32)